name: Test Report

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v2.5.0
        with:
          artifact: test-reports        # artifact uploaded by the Lint workflow
          name: Reference Model Tests   # name of the check run created
          path: "*.xml"                 # path to test results inside the artifact zip
          reporter: java-junit          # format of test results
